version: '3.7'
services:
    #app:
    #    build:
    #      context: .
    #      dockerfile: ./Dockerfile
    #    ports:
    #      - '8080:8080'
    #    depends_on:
    #      - postgres
    postgres:
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
        # TODO komentar
          - ./create_table.sql:/docker-entrypoint-initdb.d/create_tables.sql

    adminer:
        image: adminer
        restart: always
        ports:
          - '9090:8080'